In [1]:
import numpy as np
import pythreejs as p3
from matplotlib import cm

In [2]:
N = 100
M = 50
xx = np.arange(N, dtype=np.float32)
yy = np.arange(M, dtype=np.float32)
x, y = np.meshgrid(xx, yy,indexing="ij")
# y, x = np.meshgrid(yy, xx)
b = N/20.0
c = M/2.0
r = np.sqrt(((x-c)/b)**2 + (y/b)**2)
a = np.sin(r)
a.shape

(100, 50)

In [3]:
scalar_map = cm.ScalarMappable(cmap='viridis')
colors = scalar_map.to_rgba(a.flat).astype(np.float32)

In [4]:
vertices = np.array([x.flatten(), y.flatten(), np.zeros_like(x.flatten())], dtype='float32').T
vertices.shape

(5000, 3)

In [5]:
geom = p3.CylinderGeometry(
    radiusTop=1,
    radiusBottom=1,
    height=1,
    radialSegments=10,
    heightSegments=1,
    openEnded=False,
    thetaStart=0,
    thetaLength=2.0*np.pi)
morph = p3.BufferGeometry.from_geometry(geom)

In [6]:
morph.attributes["position"].array

array([[ 0.0000000e+00,  5.0000000e-01,  1.0000000e+00],
       [ 0.0000000e+00, -5.0000000e-01,  1.0000000e+00],
       [ 5.8778524e-01,  5.0000000e-01,  8.0901700e-01],
       [ 0.0000000e+00, -5.0000000e-01,  1.0000000e+00],
       [ 5.8778524e-01, -5.0000000e-01,  8.0901700e-01],
       [ 5.8778524e-01,  5.0000000e-01,  8.0901700e-01],
       [ 5.8778524e-01,  5.0000000e-01,  8.0901700e-01],
       [ 5.8778524e-01, -5.0000000e-01,  8.0901700e-01],
       [ 9.5105654e-01,  5.0000000e-01,  3.0901700e-01],
       [ 5.8778524e-01, -5.0000000e-01,  8.0901700e-01],
       [ 9.5105654e-01, -5.0000000e-01,  3.0901700e-01],
       [ 9.5105654e-01,  5.0000000e-01,  3.0901700e-01],
       [ 9.5105654e-01,  5.0000000e-01,  3.0901700e-01],
       [ 9.5105654e-01, -5.0000000e-01,  3.0901700e-01],
       [ 9.5105654e-01,  5.0000000e-01, -3.0901700e-01],
       [ 9.5105654e-01, -5.0000000e-01,  3.0901700e-01],
       [ 9.5105654e-01, -5.0000000e-01, -3.0901700e-01],
       [ 9.5105654e-01,  5.0000

In [7]:
p3.WireframeGeometry(geom)

Preview(child=WireframeGeometry(geometry=CylinderGeometry(radialSegments=10)), shadowMap=WebGLShadowMap())

In [8]:
grid = p3.PlaneGeometry(
    width=N,
    height=M,
    widthSegments=N,
    heightSegments=M)

In [9]:
grid.vertices

AttributeError: 'PlaneGeometry' object has no attribute 'vertices'

In [10]:
# geom.attributes["color"] = p3.BufferAttribute(array=np.repeat(colors[:, :3], 6, axis=0))
geom.attributes["color"] = p3.BufferAttribute(array=np.random.random([30000, 3]))

/home/nvaytet/software/miniconda3/lib/python3.7/site-packages/pythreejs/traits.py:191: UserWarning: 64-bit data types not supported for WebGL data, casting to 32-bit.
  warnings.warn('64-bit data types not supported for WebGL '


AttributeError: 'CylinderGeometry' object has no attribute 'attributes'

In [11]:
material = p3.ShaderMaterial(
    vertexShader='''
precision highp float;
varying vec3 vColor;
varying vec3 vPosition;
void main() {
    vPosition = position;
    vColor = color;
    gl_Position = projectionMatrix * modelViewMatrix * vec4( vPosition, 1.0 );
}
''',
    fragmentShader='''
precision highp float;
varying vec3 vColor;
void main() {
    gl_FragColor = vec4( vColor.rgb, 1.0 );
}
''',
    vertexColors='VertexColors'
)

In [12]:
# material=p3.MeshBasicMaterial(vertexColors='FaceColors')

In [13]:
surf = p3.Mesh(geometry=geom, material=material)

In [14]:
width=600
height=400
camera = p3.PerspectiveCamera(position=[0, 0, 100],
                              aspect=width / height)
key_light = p3.DirectionalLight(position=[0, 10, 10])
ambient_light = p3.AmbientLight()
scene = p3.Scene(children=[surf, camera, key_light, ambient_light], background="red")
controller = p3.OrbitControls(controlling=camera)
renderer = p3.Renderer(camera=camera, scene=scene,
                                 controls=[controller],
                                 width=width,
                                 height=height)
renderer

Renderer(camera=PerspectiveCamera(aspect=1.5, position=(0.0, 0.0, 100.0), quaternion=(0.0, 0.0, 0.0, 1.0), sca…

In [32]:
import numpy as np
x = np.arange(5.)
y = np.arange(5., 9.)
x

array([0., 1., 2., 3., 4.])

In [33]:
arr_x = np.zeros(2 * (x.shape[0] - 1), dtype=x.dtype)
arr_x[::2] = x[:-1]
arr_x[1::2] = x[1:]
print(arr_x)
arr_y = np.zeros(2 * (y.shape[0] - 1), dtype=x.dtype)
arr_y[::2] = y[:-1]
arr_y[1::2] = y[1:]
print(arr_y)

[0. 1. 1. 2. 2. 3. 3. 4.]
[5. 6. 6. 7. 7. 8.]


In [34]:
xx, yy = np.meshgrid(arr_x, arr_y)
xx.shape

(6, 8)

In [35]:
yy

array([[5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7.],
       [7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8.]])

In [36]:
16*4

64

In [40]:
a = np.array([xx.ravel(), yy.ravel()]).T
len(a)

48

In [38]:
nx=8
face_elem = [[0, 1, nx], [1, nx+1, nx]]
face_elem

[[0, 1, 8], [1, 9, 8]]

In [44]:
npixels = 12
np.tile(face_elem, [npixels, 1])

array([[0, 1, 8],
       [1, 9, 8],
       [0, 1, 8],
       [1, 9, 8],
       [0, 1, 8],
       [1, 9, 8],
       [0, 1, 8],
       [1, 9, 8],
       [0, 1, 8],
       [1, 9, 8],
       [0, 1, 8],
       [1, 9, 8],
       [0, 1, 8],
       [1, 9, 8],
       [0, 1, 8],
       [1, 9, 8],
       [0, 1, 8],
       [1, 9, 8],
       [0, 1, 8],
       [1, 9, 8],
       [0, 1, 8],
       [1, 9, 8],
       [0, 1, 8],
       [1, 9, 8]])

In [48]:
np.repeat(np.arange(0, npixels*2, 2, dtype=np.uint32), 2*3, axis=0).reshape(npixels*2, 3)

array([[ 0,  0,  0],
       [ 0,  0,  0],
       [ 2,  2,  2],
       [ 2,  2,  2],
       [ 4,  4,  4],
       [ 4,  4,  4],
       [ 6,  6,  6],
       [ 6,  6,  6],
       [ 8,  8,  8],
       [ 8,  8,  8],
       [10, 10, 10],
       [10, 10, 10],
       [12, 12, 12],
       [12, 12, 12],
       [14, 14, 14],
       [14, 14, 14],
       [16, 16, 16],
       [16, 16, 16],
       [18, 18, 18],
       [18, 18, 18],
       [20, 20, 20],
       [20, 20, 20],
       [22, 22, 22],
       [22, 22, 22]], dtype=uint32)

In [ ]:
np.tile(face_elem, [npixels, 1]) + np.repeat(
    np.arange(0, npixels*2, 2, dtype=np.uint32), 2*3, axis=0).reshape(npixels*2, 3) + np.repeat(
    np.arange(0, nx*2 * (ny), 2, dtype=np.uint32), 2*3, axis=0).reshape(npixels*2, 3))

In [49]:
nx = 4
ny = 2

In [51]:
np.repeat(np.arange(0, (nx*2)*(ny), nx*2, dtype=np.uint32), (nx*2)*3, axis=0)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8,
       8, 8, 8, 8], dtype=uint32)