In [1]:
import pythreejs as p3
import numpy as np

In [29]:
box = p3.BoxGeometry(width=2, widthSegments=1,
    heightSegments=1,
    depthSegments=1)
morph = p3.BufferGeometry.from_geometry(box)

In [30]:
morph.attributes

{'position': BufferAttribute(array=array([[ 1. ,  0.5,  0.5],
        [ 1. , -0.5,  0.5],
        [ 1. ,  0.5, -0.5],
        [ 1. , -0.5,  0.5],
        [ 1. , -0.5, -0.5],
        [ 1. ,  0.5, -0.5],
        [-1. ,  0.5, -0.5],
        [-1. , -0.5, -0.5],
        [-1. ,  0.5,  0.5],
        [-1. , -0.5, -0.5],
        [-1. , -0.5,  0.5],
        [-1. ,  0.5,  0.5],
        [-1. ,  0.5, -0.5],
        [-1. ,  0.5,  0.5],
        [ 1. ,  0.5, -0.5],
        [-1. ,  0.5,  0.5],
        [ 1. ,  0.5,  0.5],
        [ 1. ,  0.5, -0.5],
        [-1. , -0.5,  0.5],
        [-1. , -0.5, -0.5],
        [ 1. , -0.5,  0.5],
        [-1. , -0.5, -0.5],
        [ 1. , -0.5, -0.5],
        [ 1. , -0.5,  0.5],
        [-1. ,  0.5,  0.5],
        [-1. , -0.5,  0.5],
        [ 1. ,  0.5,  0.5],
        [-1. , -0.5,  0.5],
        [ 1. , -0.5,  0.5],
        [ 1. ,  0.5,  0.5],
        [ 1. ,  0.5, -0.5],
        [ 1. , -0.5, -0.5],
        [-1. ,  0.5, -0.5],
        [ 1. , -0.5, -0.5],
        [-1. ,

In [57]:
# vertices = np.asarray([
#     [0, 0, 0],
#     [0, 1, 0],
#     [1, 0, 0],
#     [1, 1, 0],
#     [1, 0, 0],
#     [1, 1, 0],
#     [2, 0, 0],
#     [2, 1, 0],
# ], dtype='float32')

# vertices = morph.attributes["position"].array

vertices = np.tile(morph.attributes["position"].array, [2, 1]) + np.repeat(offsets, 36, axis=0)

faces = np.arange(72, dtype=np.uint)

# faces = np.asarray([
#     [0, 2, 1],
#     [2, 3, 1],
#     [4, 6, 5],
#     [6, 7, 5],
# ], dtype='uint16').ravel()  # We need to flatten index array


# vertexcolors = np.asarray([(0,0,1), (0,0,1), (0,0,1), (0,0,1),
#                            (1,0,0), (1,0,0), (1,0,0), (1,0,0)], dtype='float32')

# vertexcolors = np.repeat([0,0,1], 36).astype(np.float32)
# vertexcolors = np.array([[0,0,1]] * 36).astype(np.float32)

vertexcolors = np.repeat([[0,0,1], [1,0,0]], 36, axis=0).astype(np.float32)

cubeGeometry = p3.BufferGeometry(attributes=dict(
    position=p3.BufferAttribute(vertices, normalized=False),
    index=p3.BufferAttribute(faces, normalized=False),
    color=p3.BufferAttribute(vertexcolors),
))

mesh = p3.Mesh(
    geometry=cubeGeometry,
    material=p3.MeshBasicMaterial(vertexColors='VertexColors'),
    position=[-0.5, -0.5, -0.5]   # Center the cube
)


# cCube = p3.PerspectiveCamera(
#     position=[3, 3, 3], fov=20,
#     children=[DirectionalLight(color='#ffffff', position=[-3, 5, 1], intensity=0.5)])
# sceneCube = p3.Scene(children=[myobjectCube, cCube, AmbientLight(color='#dddddd')])

# rendererCube = p3.Renderer(camera=cCube, background='black', background_opacity=1,
#                         scene = sceneCube, controls=[OrbitControls(controlling=cCube)])

# rendererCube


view_width = 600
view_height = 400
camera = p3.PerspectiveCamera(position=[0, 0, 2], aspect=view_width/view_height)
# key_light = p3.DirectionalLight(position=[0, 10, 10])
# ambient_light = p3.AmbientLight()
scene = p3.Scene(children=[mesh, camera], background="#000000")
controller = p3.OrbitControls(controlling=camera)
renderer = p3.Renderer(camera=camera, scene=scene, controls=[controller],
                    width=view_width, height=view_height)
renderer

Renderer(camera=PerspectiveCamera(aspect=1.5, position=(0.0, 0.0, 2.0), quaternion=(0.0, 0.0, 0.0, 1.0), scale…

In [35]:
cubeGeometry.attributes

{'position': BufferAttribute(array=array([[ 1. ,  0.5,  0.5],
        [ 1. , -0.5,  0.5],
        [ 1. ,  0.5, -0.5],
        [ 1. , -0.5,  0.5],
        [ 1. , -0.5, -0.5],
        [ 1. ,  0.5, -0.5],
        [-1. ,  0.5, -0.5],
        [-1. , -0.5, -0.5],
        [-1. ,  0.5,  0.5],
        [-1. , -0.5, -0.5],
        [-1. , -0.5,  0.5],
        [-1. ,  0.5,  0.5],
        [-1. ,  0.5, -0.5],
        [-1. ,  0.5,  0.5],
        [ 1. ,  0.5, -0.5],
        [-1. ,  0.5,  0.5],
        [ 1. ,  0.5,  0.5],
        [ 1. ,  0.5, -0.5],
        [-1. , -0.5,  0.5],
        [-1. , -0.5, -0.5],
        [ 1. , -0.5,  0.5],
        [-1. , -0.5, -0.5],
        [ 1. , -0.5, -0.5],
        [ 1. , -0.5,  0.5],
        [-1. ,  0.5,  0.5],
        [-1. , -0.5,  0.5],
        [ 1. ,  0.5,  0.5],
        [-1. , -0.5,  0.5],
        [ 1. , -0.5,  0.5],
        [ 1. ,  0.5,  0.5],
        [ 1. ,  0.5, -0.5],
        [ 1. , -0.5, -0.5],
        [-1. ,  0.5, -0.5],
        [ 1. , -0.5, -0.5],
        [-1. ,

In [42]:
np.array([[0,0,1]] * 36).shape

(36, 3)

In [51]:
offsets = [[0, 0, 0], [10, 10 ,5]]

In [52]:
np.tile(morph.attributes["position"].array, [2, 1]) + np.repeat(offsets, 36, axis=0)

array([[ 1. ,  0.5,  0.5],
       [ 1. , -0.5,  0.5],
       [ 1. ,  0.5, -0.5],
       [ 1. , -0.5,  0.5],
       [ 1. , -0.5, -0.5],
       [ 1. ,  0.5, -0.5],
       [-1. ,  0.5, -0.5],
       [-1. , -0.5, -0.5],
       [-1. ,  0.5,  0.5],
       [-1. , -0.5, -0.5],
       [-1. , -0.5,  0.5],
       [-1. ,  0.5,  0.5],
       [-1. ,  0.5, -0.5],
       [-1. ,  0.5,  0.5],
       [ 1. ,  0.5, -0.5],
       [-1. ,  0.5,  0.5],
       [ 1. ,  0.5,  0.5],
       [ 1. ,  0.5, -0.5],
       [-1. , -0.5,  0.5],
       [-1. , -0.5, -0.5],
       [ 1. , -0.5,  0.5],
       [-1. , -0.5, -0.5],
       [ 1. , -0.5, -0.5],
       [ 1. , -0.5,  0.5],
       [-1. ,  0.5,  0.5],
       [-1. , -0.5,  0.5],
       [ 1. ,  0.5,  0.5],
       [-1. , -0.5,  0.5],
       [ 1. , -0.5,  0.5],
       [ 1. ,  0.5,  0.5],
       [ 1. ,  0.5, -0.5],
       [ 1. , -0.5, -0.5],
       [-1. ,  0.5, -0.5],
       [ 1. , -0.5, -0.5],
       [-1. , -0.5, -0.5],
       [-1. ,  0.5, -0.5],
       [11. , 10.5,  5.5],
 

In [49]:
morph.attributes["position"].array

array([[ 1. ,  0.5,  0.5],
       [ 1. , -0.5,  0.5],
       [ 1. ,  0.5, -0.5],
       [ 1. , -0.5,  0.5],
       [ 1. , -0.5, -0.5],
       [ 1. ,  0.5, -0.5],
       [-1. ,  0.5, -0.5],
       [-1. , -0.5, -0.5],
       [-1. ,  0.5,  0.5],
       [-1. , -0.5, -0.5],
       [-1. , -0.5,  0.5],
       [-1. ,  0.5,  0.5],
       [-1. ,  0.5, -0.5],
       [-1. ,  0.5,  0.5],
       [ 1. ,  0.5, -0.5],
       [-1. ,  0.5,  0.5],
       [ 1. ,  0.5,  0.5],
       [ 1. ,  0.5, -0.5],
       [-1. , -0.5,  0.5],
       [-1. , -0.5, -0.5],
       [ 1. , -0.5,  0.5],
       [-1. , -0.5, -0.5],
       [ 1. , -0.5, -0.5],
       [ 1. , -0.5,  0.5],
       [-1. ,  0.5,  0.5],
       [-1. , -0.5,  0.5],
       [ 1. ,  0.5,  0.5],
       [-1. , -0.5,  0.5],
       [ 1. , -0.5,  0.5],
       [ 1. ,  0.5,  0.5],
       [ 1. ,  0.5, -0.5],
       [ 1. , -0.5, -0.5],
       [-1. ,  0.5, -0.5],
       [ 1. , -0.5, -0.5],
       [-1. , -0.5, -0.5],
       [-1. ,  0.5, -0.5]], dtype=float32)

In [55]:
np.repeat([[0,0,1], [1,0,0]], 36, axis=0)

array([[0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1,

In [82]:
# box = p3.BoxBufferGeometry(width=2, widthSegments=1,
#     heightSegments=1,
#     depthSegments=1)
box = p3.BoxGeometry(width=2, widthSegments=1,
    heightSegments=1,
    depthSegments=1)
morph = p3.BufferGeometry.from_geometry(box)

In [88]:
size_x = 1.0
size_y = 1.0
size_z = 1.0
detector_shape = np.array([[ 0.5*size_x,  0.5*size_y,  0.5*size_z],
                           [ 0.5*size_x, -0.5*size_y,  0.5*size_z],
                           [ 0.5*size_x,  0.5*size_y, -0.5*size_z],
                           [ 0.5*size_x, -0.5*size_y,  0.5*size_z],
                           [ 0.5*size_x, -0.5*size_y, -0.5*size_z],
                           [ 0.5*size_x,  0.5*size_y, -0.5*size_z],
                           [-0.5*size_x,  0.5*size_y, -0.5*size_z],
                           [-0.5*size_x, -0.5*size_y, -0.5*size_z],
                           [-0.5*size_x,  0.5*size_y,  0.5*size_z],
                           [-0.5*size_x, -0.5*size_y, -0.5*size_z],
                           [-0.5*size_x, -0.5*size_y,  0.5*size_z],
                           [-0.5*size_x,  0.5*size_y,  0.5*size_z],
                           [-0.5*size_x,  0.5*size_y, -0.5*size_z],
                           [-0.5*size_x,  0.5*size_y,  0.5*size_z],
                           [ 0.5*size_x,  0.5*size_y, -0.5*size_z],
                           [-0.5*size_x,  0.5*size_y,  0.5*size_z],
                           [ 0.5*size_x,  0.5*size_y,  0.5*size_z],
                           [ 0.5*size_x,  0.5*size_y, -0.5*size_z],
                           [-0.5*size_x, -0.5*size_y,  0.5*size_z],
                           [-0.5*size_x, -0.5*size_y, -0.5*size_z],
                           [ 0.5*size_x, -0.5*size_y,  0.5*size_z],
                           [-0.5*size_x, -0.5*size_y, -0.5*size_z],
                           [ 0.5*size_x, -0.5*size_y, -0.5*size_z],
                           [ 0.5*size_x, -0.5*size_y,  0.5*size_z],
                           [-0.5*size_x,  0.5*size_y,  0.5*size_z],
                           [-0.5*size_x, -0.5*size_y,  0.5*size_z],
                           [ 0.5*size_x,  0.5*size_y,  0.5*size_z],
                           [-0.5*size_x, -0.5*size_y,  0.5*size_z],
                           [ 0.5*size_x, -0.5*size_y,  0.5*size_z],
                           [ 0.5*size_x,  0.5*size_y,  0.5*size_z],
                           [ 0.5*size_x,  0.5*size_y, -0.5*size_z],
                           [ 0.5*size_x, -0.5*size_y, -0.5*size_z],
                           [-0.5*size_x,  0.5*size_y, -0.5*size_z],
                           [ 0.5*size_x, -0.5*size_y, -0.5*size_z],
                           [-0.5*size_x, -0.5*size_y, -0.5*size_z],
                           [-0.5*size_x,  0.5*size_y, -0.5*size_z]], dtype=np.float32)

In [91]:
N = 1000
M = len(morph.attributes["position"].array)

offsets = (np.random.random([N, 3]).astype(np.float32) - 0.5) * 50.0

# vertices = np.tile(morph.attributes["position"].array, [N, 1]) + np.repeat(offsets, M, axis=0)
vertices = np.tile(detector_shape, [N, 1]) + np.repeat(offsets, M, axis=0)

faces = np.arange(M * N, dtype=np.uint)

vertexcolors = np.repeat(np.random.random([N, 3]), M, axis=0).astype(np.float32)

print(vertices.shape)
print(faces.shape)
print(vertexcolors.shape)

cubeGeometry = p3.BufferGeometry(attributes=dict(
    position=p3.BufferAttribute(vertices, normalized=False),
    index=p3.BufferAttribute(faces, normalized=False),
    color=p3.BufferAttribute(vertexcolors),
))

mesh = p3.Mesh(
    geometry=cubeGeometry,
    material=p3.MeshBasicMaterial(vertexColors='VertexColors'),
#     position=[-0.5, -0.5, -0.5]   # Center the cube
)


# cCube = p3.PerspectiveCamera(
#     position=[3, 3, 3], fov=20,
#     children=[DirectionalLight(color='#ffffff', position=[-3, 5, 1], intensity=0.5)])
# sceneCube = p3.Scene(children=[myobjectCube, cCube, AmbientLight(color='#dddddd')])

# rendererCube = p3.Renderer(camera=cCube, background='black', background_opacity=1,
#                         scene = sceneCube, controls=[OrbitControls(controlling=cCube)])

# rendererCube


view_width = 600
view_height = 400
camera = p3.PerspectiveCamera(position=[0, 0, 50], aspect=view_width/view_height)
# key_light = p3.DirectionalLight(position=[0, 10, 10])
# ambient_light = p3.AmbientLight()
scene = p3.Scene(children=[mesh, camera], background="#000000")
controller = p3.OrbitControls(controlling=camera)
renderer = p3.Renderer(camera=camera, scene=scene, controls=[controller],
                    width=view_width, height=view_height)
renderer

(36000, 3)
(36000,)
(36000, 3)


Renderer(camera=PerspectiveCamera(aspect=1.5, position=(0.0, 0.0, 50.0), quaternion=(0.0, 0.0, 0.0, 1.0), scal…

In [73]:
cubeGeometry.attributes["color"].array= c

In [72]:
c = np.repeat(np.random.random([N, 3]), 36, axis=0).astype(np.float32)

In [59]:
offsets

array([[43.290897 , 38.57635  , 48.050064 ],
       [47.747612 , 38.237946 , 11.714894 ],
       [ 8.991169 , 30.666653 , 19.217476 ],
       [ 4.7038965, 23.012762 , 45.160477 ],
       [19.233856 , 10.275364 , 11.79136  ],
       [49.535145 , 32.8804   , 22.962154 ],
       [43.2273   , 27.286238 , 35.881706 ],
       [44.60778  , 48.34105  , 27.530039 ],
       [ 8.902904 , 16.046902 , 36.7019   ],
       [26.293001 , 43.316242 , 22.644676 ]], dtype=float32)

In [62]:
vertexcolors[:50]

array([[0.7768626 , 0.52654004, 0.76860076],
       [0.7768626 , 0.52654004, 0.76860076],
       [0.7768626 , 0.52654004, 0.76860076],
       [0.7768626 , 0.52654004, 0.76860076],
       [0.7768626 , 0.52654004, 0.76860076],
       [0.7768626 , 0.52654004, 0.76860076],
       [0.7768626 , 0.52654004, 0.76860076],
       [0.7768626 , 0.52654004, 0.76860076],
       [0.7768626 , 0.52654004, 0.76860076],
       [0.7768626 , 0.52654004, 0.76860076],
       [0.7768626 , 0.52654004, 0.76860076],
       [0.7768626 , 0.52654004, 0.76860076],
       [0.7768626 , 0.52654004, 0.76860076],
       [0.7768626 , 0.52654004, 0.76860076],
       [0.7768626 , 0.52654004, 0.76860076],
       [0.7768626 , 0.52654004, 0.76860076],
       [0.7768626 , 0.52654004, 0.76860076],
       [0.7768626 , 0.52654004, 0.76860076],
       [0.7768626 , 0.52654004, 0.76860076],
       [0.7768626 , 0.52654004, 0.76860076],
       [0.7768626 , 0.52654004, 0.76860076],
       [0.7768626 , 0.52654004, 0.76860076],
       [0.

In [86]:
morph.attributes["position"].array

array([[ 1. ,  0.5,  0.5],
       [ 1. , -0.5,  0.5],
       [ 1. ,  0.5, -0.5],
       [ 1. , -0.5,  0.5],
       [ 1. , -0.5, -0.5],
       [ 1. ,  0.5, -0.5],
       [-1. ,  0.5, -0.5],
       [-1. , -0.5, -0.5],
       [-1. ,  0.5,  0.5],
       [-1. , -0.5, -0.5],
       [-1. , -0.5,  0.5],
       [-1. ,  0.5,  0.5],
       [-1. ,  0.5, -0.5],
       [-1. ,  0.5,  0.5],
       [ 1. ,  0.5, -0.5],
       [-1. ,  0.5,  0.5],
       [ 1. ,  0.5,  0.5],
       [ 1. ,  0.5, -0.5],
       [-1. , -0.5,  0.5],
       [-1. , -0.5, -0.5],
       [ 1. , -0.5,  0.5],
       [-1. , -0.5, -0.5],
       [ 1. , -0.5, -0.5],
       [ 1. , -0.5,  0.5],
       [-1. ,  0.5,  0.5],
       [-1. , -0.5,  0.5],
       [ 1. ,  0.5,  0.5],
       [-1. , -0.5,  0.5],
       [ 1. , -0.5,  0.5],
       [ 1. ,  0.5,  0.5],
       [ 1. ,  0.5, -0.5],
       [ 1. , -0.5, -0.5],
       [-1. ,  0.5, -0.5],
       [ 1. , -0.5, -0.5],
       [-1. , -0.5, -0.5],
       [-1. ,  0.5, -0.5]], dtype=float32)

In [95]:
size_x = 1.0
size_y = 1.0
size_z = 1.0
detector_shape = np.array([[ 0.5*size_x,  0.5*size_y,  0.5*size_z],
                           [ 0.5*size_x, -0.5*size_y,  0.5*size_z],
                           [ 0.5*size_x,  0.5*size_y, -0.5*size_z],
                           [ 0.5*size_x, -0.5*size_y,  0.5*size_z],
                           [ 0.5*size_x, -0.5*size_y, -0.5*size_z],
                           [ 0.5*size_x,  0.5*size_y, -0.5*size_z],
                           [-0.5*size_x,  0.5*size_y, -0.5*size_z],
                           [-0.5*size_x, -0.5*size_y, -0.5*size_z],
                           [-0.5*size_x,  0.5*size_y,  0.5*size_z],
                           [-0.5*size_x, -0.5*size_y, -0.5*size_z],
                           [-0.5*size_x, -0.5*size_y,  0.5*size_z],
                           [-0.5*size_x,  0.5*size_y,  0.5*size_z],
                           [-0.5*size_x,  0.5*size_y, -0.5*size_z],
                           [-0.5*size_x,  0.5*size_y,  0.5*size_z],
                           [ 0.5*size_x,  0.5*size_y, -0.5*size_z],
                           [-0.5*size_x,  0.5*size_y,  0.5*size_z],
                           [ 0.5*size_x,  0.5*size_y,  0.5*size_z],
                           [ 0.5*size_x,  0.5*size_y, -0.5*size_z],
                           [-0.5*size_x, -0.5*size_y,  0.5*size_z],
                           [-0.5*size_x, -0.5*size_y, -0.5*size_z],
                           [ 0.5*size_x, -0.5*size_y,  0.5*size_z],
                           [-0.5*size_x, -0.5*size_y, -0.5*size_z],
                           [ 0.5*size_x, -0.5*size_y, -0.5*size_z],
                           [ 0.5*size_x, -0.5*size_y,  0.5*size_z],
                           [-0.5*size_x,  0.5*size_y,  0.5*size_z],
                           [-0.5*size_x, -0.5*size_y,  0.5*size_z],
                           [ 0.5*size_x,  0.5*size_y,  0.5*size_z],
                           [-0.5*size_x, -0.5*size_y,  0.5*size_z],
                           [ 0.5*size_x, -0.5*size_y,  0.5*size_z],
                           [ 0.5*size_x,  0.5*size_y,  0.5*size_z],
                           [ 0.5*size_x,  0.5*size_y, -0.5*size_z],
                           [ 0.5*size_x, -0.5*size_y, -0.5*size_z],
                           [-0.5*size_x,  0.5*size_y, -0.5*size_z],
                           [ 0.5*size_x, -0.5*size_y, -0.5*size_z],
                           [-0.5*size_x, -0.5*size_y, -0.5*size_z],
                           [-0.5*size_x,  0.5*size_y, -0.5*size_z]], dtype=np.float32)



nverts = 1000
ndets = 36

offsets = (np.random.random([nverts, 3]).astype(np.float32) - 0.5) * 50.0

# vertices = np.tile(morph.attributes["position"].array, [N, 1]) + np.repeat(offsets, M, axis=0)
vertices = np.tile(detector_shape, [nverts, 1]) + np.repeat(offsets, ndets, axis=0)

faces = np.arange(ndets * nverts, dtype=np.uint)

vertexcolors = np.repeat(np.random.random([nverts, 3]), ndets, axis=0).astype(np.float32)

print(vertices.shape)
print(faces.shape)
print(vertexcolors.shape)

geometry = p3.BufferGeometry(attributes=dict(
    position=p3.BufferAttribute(vertices, normalized=False),
    index=p3.BufferAttribute(faces, normalized=False),
    color=p3.BufferAttribute(vertexcolors),
))

mesh = p3.Mesh(
    geometry=geometry,
    material=p3.MeshBasicMaterial(vertexColors='VertexColors'),
#     position=[-0.5, -0.5, -0.5]   # Center the cube
)








# # The point cloud and its properties
# pts = p3.BufferAttribute(array=det_pos)
# colors = p3.BufferAttribute(
#     array=np.zeros([np.shape(det_pos)[0], 4], dtype=np.float32))
# geometry = p3.BufferGeometry(attributes={
#     'position': pts,
#     'color': colors
# })
# material = p3.PointsMaterial(vertexColors='VertexColors',
#                                        size=max(size),
#                                        map=texture,
#                                        depthTest=False,
#                                        transparent=True)
# pcl = p3.Points(geometry=geometry,
#                           material=material)
# Add the red green blue axes helper
axes_helper = p3.AxesHelper(100)

view_width = 600
view_height = 400

# Create the threejs scene with ambient light and camera
camera = p3.PerspectiveCamera(position=[10] * 3,
                                        aspect=view_width /
                                        view_height)
# key_light = p3.DirectionalLight(position=[0, 10, 10])
# ambient_light = p3.AmbientLight()

scene = p3.Scene(children=[
    mesh, camera, #key_light, ambient_light,
    axes_helper
], background="#DDDDDD")
controller = p3.OrbitControls(controlling=camera)

# Render the scene into a widget
renderer = p3.Renderer(camera=camera,
                                 scene=scene,
                                 controls=[controller],
                                 width=view_width,
                                 height=view_height)
renderer

(36000, 3)
(36000,)
(36000, 3)


Renderer(camera=PerspectiveCamera(aspect=1.5, position=(10.0, 10.0, 10.0), quaternion=(0.0, 0.0, 0.0, 1.0), sc…